//
//  UIViewController+Extensions.swift
//  Created by Ilham Prabawa on 30/03/23.
//  Copyright (c) 2023 Ilham Prabawa. All rights reserved.
//
//  This file was generated by the Advanced Arch Xcode Templates so
//  you can apply Advanced Architecture to your iOS project.


import UIKit

extension UIViewController {
  
  // MARK: - Methods
  public func addFullScreen(childViewController child: UIViewController) {
    guard child.parent == nil else {
      return
    }
    
    addChild(child)
    view.addSubview(child.view)
    
    child.view.translatesAutoresizingMaskIntoConstraints = false
    let constraints = [
      view.leadingAnchor.constraint(equalTo: child.view.leadingAnchor),
      view.trailingAnchor.constraint(equalTo: child.view.trailingAnchor),
      view.topAnchor.constraint(equalTo: child.view.topAnchor),
      view.bottomAnchor.constraint(equalTo: child.view.bottomAnchor)
    ]
    constraints.forEach { $0.isActive = true }
    view.addConstraints(constraints)
    
    child.didMove(toParent: self)
  }
  
  public func remove(childViewController child: UIViewController?) {
    guard let child = child else {
      return
    }
    
    guard child.parent != nil else {
      return
    }
    
    child.willMove(toParent: nil)
    child.view.removeFromSuperview()
    child.removeFromParent()
  }
  
  public func showErrorAlert(title: String, msg: String) {
    let alert = UIAlertController(title: title, message: msg, preferredStyle: .alert)
    let action = UIAlertAction(title: "OK", style: .default, handler: nil)
    alert.addAction(action)
    self.present(alert, animated: true, completion: nil)
  }
  
  public func titleLabel(_ value: String) -> UILabel {
    let titleLabel = UILabel()
    titleLabel.text = value
    titleLabel.font = UIFont.systemFont(ofSize: 16, weight: .semibold)
    titleLabel.textColor = UIColor.black
    return titleLabel
  }
  
  public func standardNavBar(title: String = "") {
    navigationItem.leftBarButtonItems = [
      UIBarButtonItem(
        image: UIImage(systemName: "chevron.left")?
          .withRenderingMode(.alwaysTemplate)
          .withTintColor(.black),
        style: .plain,
        target: self,
        action: #selector(didBack)
      ),
      UIBarButtonItem(customView: titleLabel(title))
    ]
  }
  
  @objc
  open func didBack() {
    navigationController?.popViewController(animated: true)
  }
}


