//
//  NiblessNavigationController.swift
//  Created by Ilham Prabawa on 30/03/23.
//  Copyright (c) 2023 Ilham Prabawa. All rights reserved.
//
//  This file was generated by the Advanced Arch Xcode Templates so
//  you can apply Advanced Architecture to your iOS project.


import UIKit

open class NiblessNavigationController: UINavigationController {

  // MARK: - Methods
  public init() {
    super.init(nibName: nil, bundle: nil)
  }

  @available(*, unavailable,
    message: "Loading this view controller from a nib is unsupported in favor of initializer dependency injection."
  )
  public override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }

  @available(*, unavailable,
    message: "Loading this view controller from a nib is unsupported in favor of initializer dependency injection."
  )
  public required init?(coder aDecoder: NSCoder) {
    fatalError("Loading this view controller from a nib is unsupported in favor of initializer dependency injection.")
  }
}
