//
//  NiblessView.swift
//  Created by Ilham Prabawa on 30/03/23.
//  Copyright (c) 2023 Ilham Prabawa. All rights reserved.
//
//  This file was generated by the Advanced Arch Xcode Templates so
//  you can apply Advanced Architecture to your iOS project.


import UIKit

open class NiblessView: UIView {

  // MARK: - Methods
  public override init(frame: CGRect) {
    super.init(frame: frame)
  }

  @available(*, unavailable,
    message: "Loading this view from a nib is unsupported in favor of initializer dependency injection."
  )
  public required init?(coder aDecoder: NSCoder) {
    fatalError("Loading this view from a nib is unsupported in favor of initializer dependency injection.")
  }
}
